CREATE TABLE netflix (
	id INT PRIMARY KEY,
	year INT NOT NULL,
	category VARCHAR NOT NULL,
	list VARCHAR NOT NULL,
	country VARCHAR NOT NULL,
	rating VARCHAR NOT NULL
	
);
CREATE TABLE subscribers (
	id INT PRIMARY KEY,
	subscribers INT NOT NULL,
	area VARCHAR NOT NULL ,
	year INT NOT NULL
);